export const EVENT_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;

export const EVENT_STATUS_VALUES = Object.values(EVENT_STATUS);

export const EVENT_CATEGORY = {
  ACADEMIC: "ACADEMIC",
  CULTURAL: "CULTURAL",
  SPORTS: "SPORTS",
  WORKSHOP: "WORKSHOP",
  SEMINAR: "SEMINAR",
  AWARENESS: "AWARENESS",
  CELEBRATION: "CELEBRATION",
  OTHER: "OTHER",
} as const;

export const EVENT_CATEGORY_VALUES = Object.values(EVENT_CATEGORY);